### ISSUE TITLE
需要震動手機的功能

### ISSUE THREAD

**Issue by K4Lok** [UM-ARK/UM-All-Frontend#103]
### 1. 使用了React Native內置的[Vibration](https://reactnative.dev/docs/vibration)震動方法並沒有回應。
官方[issues](https://github.com/facebook/react-native/issues/32352)中目前並沒有解決方案
這個[方法](https://www.reddit.com/r/reactnative/comments/b3ewlp/is_it_possible_to_do_a_click_vibrate_in_ios/)也不行

### 2. 嘗試了第三方依賴包[react-native-haptic-feedback](https://github.com/junina-de/react-native-haptic-feedback)。
以嘗試文檔中的兩種方法去安裝這個包，也是沒有效果

![Screenshot 2022-07-21 at 11 48 01 PM](https://user-images.githubusercontent.com/82365010/180328849-252b80cc-968c-466b-8b5b-b5330d6d6bcd.png)

需要幫助去測試。

**Comment by yyyyyyounger** [comment]
在什麼情景下需要震動手機呢？

**Comment by K4Lok** [comment]
> 在什麼情景下需要震動手機呢？

例如長按複製link或email時，來個小震動讓用戶很直覺知道文本複製了，不用一直在按。

**Comment by yyyyyyounger** [comment]
已成功使用該包。
