### ISSUE TITLE
英文版支持 - English Version Support

### ISSUE THREAD

**Issue by yyyyyyounger** [UM-ARK/UM-All-Frontend#160]
判斷手機默認顯示語言，切換英文版顯示

**Comment by yyyyyyounger** [comment]
似乎需要用JSON把所有中文標題改為英文，是個大工程。
而且排版可能需要大改，且不知道某功能最簡單的英語表達是什麼，暫且擱置，等待有緣人

**Comment by YanzhenHuang** [comment]
https://blog.csdn.net/z372574152/article/details/105121458

**Comment by YanzhenHuang** [comment]
https://www.geeksforgeeks.org/multi-language-support-in-react-native/

**Comment by yyyyyyounger** [comment]
> https://www.geeksforgeeks.org/multi-language-support-in-react-native/

https://react.i18next.com/guides/quick-start
react i18n 可以在類組件中使用
