### ISSUE TITLE
課表模擬Import ISW 課表數據bug

### ISSUE THREAD

**Issue by yyyyyyounger** [UM-ARK/UM-All-Frontend#243]
三合一課程無法直接導入

例如：
TimeDay	Mon	Tue	Wed	Thur	Fri	Sat	Sun
10:00	10:00-11:15 GESB1001/1002/1003(002)
E4-1051
(Lecture)	-	-	10:00-11:15 GESB1001/1002/1003(002)
E4-1051
(Lecture)	-	10:00-11:15 ECEN3002(001)
E11-1027
(Lecture)	-
10:30	-	-	-	-
11:00	11:00-12:45 ECEN3013(001)
E11-1021
(Lecture)	-	11:00-12:45 ECEN3013(001)
E11-1021
(Lab/Tutorial)	-
11:30	-	-	-	-	-
12:00	-	-	-	-	-
12:30	-	-	-	-	-
13:00	-	-	-	-	-	-	-
13:30	-	-	-	-	-	-	-
14:00	-	-	-	-	-	-	-
14:30	14:30-15:45 GELH2000(001)
E3-2032
(Lecture)	-	-	14:30-15:45 GELH2000(001)
E3-2032
(Lecture)	-	-	-
15:00	-	-	-	-	-
15:30	-	-	-	-	-
16:00	-	-	-	16:00-18:45 GELH2001(001)
E3-4042
(Lecture)	-	-	-
16:30	-	-	-	-	-	-
17:00	-	17:00-18:45 ECEN3025(001)
E11-1028
(Lecture)	-	17:00-18:45 ECEN3025(001)
E11-1028
(Lab/Tutorial)	-	-
17:30	-	-	-	-
18:00	-	-	-	-
18:30	-	-	-	-

**Comment by YanzhenHuang** [comment]
原作者Regular Expression不規範且渲染邏輯問題導致。
