### ISSUE TITLE
Page Me

### ISSUE THREAD

**Issue by BoxMars** [UM-ARK/UM-All-Frontend#6]
- [x] APP 設置
  - [x] 關於我們
  - [x] 常見問題
    - [x] 使用webview
  - [x] 我的追蹤
  - [x] 未登錄狀態的 `學生個人賬號`、`社團/組織賬號` 選擇
  - [x] 圓角樣式，盡量與全局風格一致

**Comment by yyyyyyounger** [comment]
可以嘗試使用組件庫：
https://reactnativeelements.com/docs/components/avatar
在線預覽：
https://react-native-elements.js.org/#/avatar

**Comment by yyyyyyounger** [comment]
right的小箭頭可以使用vector icon庫，而不用引用本地資源

**Comment by yyyyyyounger** [comment]
如需返回Tabbar頁面不能用navigate方法，要用jumpTo

**Comment by BoxMars** [comment]
MeScreen.js 75行与77行冲突。
![image](https://user-images.githubusercontent.com/16847158/176677910-ba60d0d6-0f0f-4977-903f-3210c19d400c.png)
