### ISSUE TITLE
識別鏈接類型文本組件封裝

### ISSUE THREAD

**Issue by yyyyyyounger** [UM-ARK/UM-All-Frontend#72]
- [x] 識別text中的https
- [x] .com
- [x] @xxx
- [x] 封裝為組件使用

## 輕按連結的部分
- [x] WebView的Header顏色
- [ ] 資料庫裡存放資料的方法
- [ ] 根據資料回傳的結構去排版（建議把連結放到固定位置，讓用戶習慣連結的位置）

## 長按連結的部分
- [x] #103

**Comment by ImK4Lok** [comment]
初步功能可以實現

<img width="200" alt="Screenshot 2022-07-16 at 7 28 11 PM" src="https://user-images.githubusercontent.com/82365010/179365698-122b6346-3718-4917-a026-34be3fdbd3b4.png">

**Comment by yyyyyyounger** [comment]
嘗試類微信聊天內容的操作邏輯，可讓用戶自行選取文本，但點擊link仍會跳轉。

**Comment by ImK4Lok** [comment]
已實現的功能
- [x] 長按連結複製
- [x] 複製後彈提示

**Comment by ImK4Lok** [comment]
## 輕按連結的部分

當前目標為先分辨連結中的內容是什麼類型（電郵、網址、等等），然後輕按時對應類型去反應：
- [ ] 電郵：開啟手機預設的電郵軟件
- [ ] 網址：直接使用我們集成的WebView去瀏覽

**Comment by ImK4Lok** [comment]
> ## 輕按連結的部分
> 當前目標為先分辨連結中的內容是什麼類型（電郵、網址、等等），然後輕按時對應類型去反應：
> 
> * [x]  電郵：開啟手機預設的電郵軟件
> * [x]  網址：直接使用我們集成的WebView去瀏覽

### 已完成輕按連結的部分，後續需要改善一下：
- [ ] WebView的Header顏色
- [ ] 資料庫裡存放資料的方法
- [ ] 根據資料回傳的結構去排版（建議把連結放到固定位置，讓用戶習慣連結的位置）

<img src="https://user-images.githubusercontent.com/82365010/180348465-a7e6ced3-94b1-4e0c-ade0-277e7d5f9eac.GIF" width="300"/>

Branch: `feature/72-HyperlinkText`

**Comment by yyyyyyounger** [comment]
Header顏色一般用固定顏色，已在最新master適配狀態欄顏色，保留主題色就好
