### ISSUE TITLE
Webview相關

### ISSUE THREAD

**Issue by yyyyyyounger** [UM-ARK/UM-All-Frontend#77]
- [x] 1 安卓的下方返回按鈕按下，理應返回上一頁，而不是關閉Webview，嘗試監聽
- [x] #80

**Comment by yyyyyyounger** [comment]
![image](https://user-images.githubusercontent.com/55580370/178666494-30be5545-8d2b-4dac-967b-8bd84ce34854.png)

**Comment by ImK4Lok** [comment]
### Bug 1
解決方法為使用[`BackHandler`](https://reactnative.dev/docs/backhandler) API增加事件監聽去連動WebView中的goBack()功能。

只不過，不知道是安卓的返回鍵有預設行為還是怎樣，返回鍵並沒有回應，需要再測試。
```js
useEffect(() => {
      // Android Only
      if(Platform.OS == "android") {
            // 把安桌端的系統返回鍵連動WebView裡的返回功能
            BackHandler.addEventListener("hardwareBackPress", handleBackPress);
        }
        return () => {
            if(Platform.OS == "android") {
                BackHandler.removeEventListener('hardwareBackPress', handleBackPress);
            }
        }
}, []);
```

**Comment by yyyyyyounger** [comment]
https://stackoverflow.com/questions/39446077/react-native-go-back-on-android-hardware-back-button-pressed
已解決，將push到新分支
