### ISSUE TITLE
2 當頁面無法上/下滑動時，前進後退按鈕佔位，使網站固有的底部Tabbar無法點擊

### ISSUE THREAD

**Issue by ImK4Lok** [UM-ARK/UM-All-Frontend#80]

**Comment by ImK4Lok** [comment]
在WebView頁面無法上/下滑動時，應該是因為網站做了手機螢幕的適配導致無法滑動。解決方案為取得當前頁面的內容長度與WebView在螢幕中的尺寸作比較，尺寸相約時自動隱藏底部Tabbar。

**Comment by yyyyyyounger** [comment]
有對此修改push新的PR嗎

**Comment by ImK4Lok** [comment]
Try to make a hover button for Android users to go back and forward if the WebView is not able to scroll in the future.

**Comment by yyyyyyounger** [comment]
Android users can use entity GoBack button to return, just can't goforward now.
