### ISSUE TITLE
資訊頁Tabbar切換Bug

### ISSUE THREAD

**Issue by yyyyyyounger** [UM-ARK/UM-All-Frontend#96]
因想添加多一個Page：澳大官方活動。
但嘗試後發現inputRange之類的有錯誤，應該是當前寫死只有3個Tab，希望增加到4個。

**Comment by ImK4Lok** [comment]
Updated with dummy value and works fine right now.
Looking for a better approach in the future.
![Simulator Screen Recording - iPhone 13 - 2022-07-20 at 21 06 54](https://user-images.githubusercontent.com/82365010/180072131-87da0e92-d7db-48de-aa41-13ed199fefe0.gif)
